/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package visao;

import dao.EncarregadoDao;
import dao.SexoDao;
import dao.EstudanteDao;
import dao.MunicipioDao;
import dao.PaisDao;
import dao.ProfissaoDao;
import dao.ProvinciaDao;
import dao.UsuarioDao;
import entity.Encarregado;
import entity.Estudante;
import entity.Municipio;
import java.awt.Color;
import java.awt.event.KeyEvent;
import java.awt.event.KeyListener;
import java.util.Date;
import java.util.List;
import javax.persistence.EntityManager;
import javax.persistence.EntityManagerFactory;
import javax.swing.DefaultComboBoxModel;
import javax.swing.DefaultListModel;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import util.JPAEntntityMannagerFactoryUtil;
import util.PictureChooser;

/**
 *
 * @author mac
 */
public class EstudanteVisao extends javax.swing.JFrame {

    private EntityManagerFactory emf = JPAEntntityMannagerFactoryUtil.em;

    /*INSTANCIA DE OBJECTO DAO*/
    private SexoDao sexoDao = new SexoDao(emf);
    private ProvinciaDao provinciaDao = new ProvinciaDao(emf);
    private EncarregadoDao encarregadoDao = new EncarregadoDao(emf);
    private ProfissaoDao profissaoDao = new ProfissaoDao(emf);
    private MunicipioDao municipioDao = new MunicipioDao(emf);
    private PaisDao paisDao = new PaisDao(emf);
    private EstudanteDao estudanteDao = new EstudanteDao(emf);
    private UsuarioDao usuarioDao = new UsuarioDao(emf);
    private Estudante estudante;
    private Encarregado encarregado;

    /*OUTROS OBJECTOS*/
    private PictureChooser image_view;
    private ImageIcon imageIcon;
    private int id_user = 0, id_estudante = 0;

    private DefaultListModel listModel = new DefaultListModel();

    public EstudanteVisao(int id_user) {
        initComponents();
        setLocationRelativeTo(null);
        this.id_user = id_user;
        this.id_estudante = id_estudante;
        jList1.setModel(listModel);
        setComponentes();
//        jocMessageLabel1.clearMessage();
        txt_iniciais_nome.addKeyListener(new TratarEventoTeclado());
        image_view = new PictureChooser();
        imageIcon = new ImageIcon();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        jSlider1 = new javax.swing.JSlider();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        txt_iniciais_nome = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        lb_foto = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        btn_salvar = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jTP_DP = new javax.swing.JTabbedPane();
        jPanel6 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txt_nomeCompleto = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        cmb_sexo = new javax.swing.JComboBox<>();
        jLabel12 = new javax.swing.JLabel();
        dc_data_validade = new com.toedter.calendar.JDateChooser();
        txt_nbi = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        txt_residencia_actual = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        txtnaturalidade = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        txt_telefone = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        txt_emial = new javax.swing.JTextField();
        jLabel28 = new javax.swing.JLabel();
        dc_data_nascimento = new com.toedter.calendar.JDateChooser();
        cmb_provincia = new javax.swing.JComboBox<>();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        cmb_municipio = new javax.swing.JComboBox<>();
        jLabel34 = new javax.swing.JLabel();
        cmb_pais = new javax.swing.JComboBox<>();
        jLabel17 = new javax.swing.JLabel();
        txt_doenca = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txt_numero_matricula = new javax.swing.JTextField();
        jPanel8 = new javax.swing.JPanel();
        jSeparator4 = new javax.swing.JSeparator();
        jLabel16 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        txtresidencia = new javax.swing.JTextField();
        jLabel24 = new javax.swing.JLabel();
        txtNomePai = new javax.swing.JTextField();
        txtNomeMae = new javax.swing.JTextField();
        jLabel25 = new javax.swing.JLabel();
        txtNomeEncarregado = new javax.swing.JTextField();
        cmb_profissao = new javax.swing.JComboBox<>();
        jLabel31 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        txtLocalTrabalho = new javax.swing.JTextField();
        jLabel33 = new javax.swing.JLabel();
        txtTelefoneEncarregado = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        lb_total_estudantes = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("null");

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Pesquisar"));

        jList1.setModel(new javax.swing.AbstractListModel<String>()
        {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jList1.addMouseListener(new java.awt.event.MouseAdapter()
        {
            public void mouseClicked(java.awt.event.MouseEvent evt)
            {
                jList1MouseClicked(evt);
            }
        });
        jList1.addKeyListener(new java.awt.event.KeyAdapter()
        {
            public void keyPressed(java.awt.event.KeyEvent evt)
            {
                jList1KeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt)
            {
                jList1KeyReleased(evt);
            }
        });
        jScrollPane1.setViewportView(jList1);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 161, Short.MAX_VALUE)
            .addComponent(txt_iniciais_nome)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(txt_iniciais_nome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 486, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(192, 208, 232));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 90, Short.MAX_VALUE)
        );

        jPanel3.setBackground(new java.awt.Color(0, 0, 0));
        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lb_foto.setBackground(new java.awt.Color(0, 0, 102));
        lb_foto.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel3.add(lb_foto, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 130, 130));

        jPanel7.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        jButton1.setText("Imprimir Ficha");
        jButton1.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jButton1ActionPerformed(evt);
            }
        });

        btn_salvar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/6665_32x32.png"))); // NOI18N
        btn_salvar.setText("Salvar");
        btn_salvar.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btn_salvarActionPerformed(evt);
            }
        });

        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/alterar_32x32_1.png"))); // NOI18N
        jButton4.setText("Alterar");
        jButton4.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jButton4ActionPerformed(evt);
            }
        });

        jButton6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Logout 32x32.png"))); // NOI18N
        jButton6.setText("Sair");
        jButton6.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jButton6ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton1)
                .addGap(257, 257, 257)
                .addComponent(btn_salvar, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                .addContainerGap(18, Short.MAX_VALUE)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_salvar)
                    .addComponent(jButton4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton6))
                .addGap(14, 14, 14))
        );

        jButton7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/actualizar_1_32x32.png"))); // NOI18N
        jButton7.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jButton7ActionPerformed(evt);
            }
        });

        jLabel1.setText("Nº Matricula");

        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel15.setText("Sexo:");

        cmb_sexo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel12.setText("Data Validade BI.:");

        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel13.setText("Nº B.I:");

        jSeparator3.setBackground(new java.awt.Color(0, 0, 153));
        jSeparator3.setOrientation(javax.swing.SwingConstants.VERTICAL);

        txt_residencia_actual.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                txt_residencia_actualActionPerformed(evt);
            }
        });

        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel14.setText("Residência Atual:");

        jLabel20.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel20.setText("Município:");

        txtnaturalidade.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                txtnaturalidadeActionPerformed(evt);
            }
        });

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder("Contactos"));

        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel9.setText("Telefone:*");

        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel10.setText("Email:");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9)
                    .addComponent(jLabel10))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 108, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txt_emial, javax.swing.GroupLayout.DEFAULT_SIZE, 214, Short.MAX_VALUE)
                    .addComponent(txt_telefone)))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_telefone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_emial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        jLabel28.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel28.setText("Data de Nascimento:");

        cmb_provincia.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cmb_provincia.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                cmb_provinciaActionPerformed(evt);
            }
        });

        jLabel29.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel29.setText("Naturalidade:");

        jLabel30.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel30.setText("Província:");

        cmb_municipio.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cmb_municipio.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                cmb_municipioActionPerformed(evt);
            }
        });

        jLabel34.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel34.setText("País:");

        cmb_pais.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cmb_pais.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                cmb_paisActionPerformed(evt);
            }
        });

        jLabel17.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel17.setText("Sofre de alguma Doença que impede a assimilação? Sim/ Não");

        txt_doenca.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                txt_doencaActionPerformed(evt);
            }
        });

        jLabel2.setText("Nome Completo: ");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel17)
                    .addComponent(txt_doenca, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(33, 33, 33)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txt_nomeCompleto)
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addComponent(txt_numero_matricula, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel14)
                            .addComponent(jLabel12)
                            .addComponent(jLabel28)
                            .addComponent(jLabel13)
                            .addComponent(jLabel15))
                        .addGap(10, 10, 10)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(dc_data_validade, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_residencia_actual, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_nbi, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(dc_data_nascimento, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cmb_sexo, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                                .addComponent(jLabel30, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(cmb_municipio, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(cmb_provincia, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel6Layout.createSequentialGroup()
                                        .addComponent(jLabel29, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(txtnaturalidade, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel6Layout.createSequentialGroup()
                                        .addComponent(jLabel34, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(cmb_pais, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addGap(45, 45, 45))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(jLabel20, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(341, 341, 341))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel6Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jSeparator3))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel6Layout.createSequentialGroup()
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addGap(12, 12, 12)
                                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel1)
                                    .addComponent(txt_numero_matricula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(12, 12, 12)
                                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel2)
                                    .addComponent(txt_nomeCompleto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(11, 11, 11)
                                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(cmb_sexo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(11, 11, 11)
                                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(dc_data_nascimento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel28, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel6Layout.createSequentialGroup()
                                        .addGap(14, 14, 14)
                                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(jLabel29, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txtnaturalidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel34, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(9, 9, 9))
                                    .addComponent(cmb_pais, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(6, 6, 6)
                                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel30, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(cmb_provincia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(7, 7, 7)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txt_nbi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(cmb_municipio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(3, 3, 3)))
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(dc_data_validade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(12, 12, 12)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txt_residencia_actual, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txt_doenca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(30, 30, 30))
        );

        jTP_DP.addTab("Dados Pessoais", jPanel6);

        jSeparator4.setBackground(new java.awt.Color(0, 0, 153));
        jSeparator4.setOrientation(javax.swing.SwingConstants.VERTICAL);

        jLabel16.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel16.setText("Nome do Encarregado:");

        jLabel23.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel23.setText("Profissão:");

        jLabel24.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel24.setText("Nome do Pai do aluno(a):");

        jLabel25.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel25.setText("Nome da Mãe do aluno(a):");

        cmb_profissao.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel31.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel31.setText("Residência:");

        jLabel32.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel32.setText("Local de trabalho:");

        jLabel33.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel33.setText("Telefone:");

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel8Layout.createSequentialGroup()
                                .addComponent(jLabel23)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(jPanel8Layout.createSequentialGroup()
                                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel32, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel31, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel8Layout.createSequentialGroup()
                                        .addComponent(txtLocalTrabalho, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 0, Short.MAX_VALUE))
                                    .addGroup(jPanel8Layout.createSequentialGroup()
                                        .addComponent(txtresidencia, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel8Layout.createSequentialGroup()
                        .addComponent(jLabel16)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel8Layout.createSequentialGroup()
                                .addComponent(cmb_profissao, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(jPanel8Layout.createSequentialGroup()
                                .addComponent(txtNomeEncarregado, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel33)
                            .addComponent(jLabel24))
                        .addGap(11, 11, 11)
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtTelefoneEncarregado, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtNomePai, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addComponent(jLabel25)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtNomeMae, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(105, Short.MAX_VALUE))
            .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel8Layout.createSequentialGroup()
                    .addGap(359, 359, 359)
                    .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(487, Short.MAX_VALUE)))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtNomeEncarregado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(34, 34, 34)
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cmb_profissao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel23, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtTelefoneEncarregado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel33, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(13, 13, 13)))
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel32, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtLocalTrabalho, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtresidencia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel31, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(147, Short.MAX_VALUE))
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel24, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtNomePai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel25, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtNomeMae, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(150, 150, 150))))
            .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jSeparator4, javax.swing.GroupLayout.DEFAULT_SIZE, 322, Short.MAX_VALUE)
                    .addContainerGap()))
        );

        jTP_DP.addTab("Dados do Encarregado", jPanel8);

        jLabel11.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel11.setText("Total de Estudantes Inscritos:");

        lb_total_estudantes.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        lb_total_estudantes.setForeground(new java.awt.Color(255, 0, 0));
        lb_total_estudantes.setText("jLabel1");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButton7)
                                .addGap(671, 671, 671))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel11)
                                .addGap(18, 18, 18)
                                .addComponent(lb_total_estudantes, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap())))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTP_DP)
                            .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(7, 7, 7)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton7))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTP_DP, javax.swing.GroupLayout.PREFERRED_SIZE, 380, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lb_total_estudantes, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:


    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
        image_view.chooseImg(lb_foto);
    }//GEN-LAST:event_jButton7ActionPerformed

    private void btn_salvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_salvarActionPerformed
        // TODO add your handling code here:
        procedimento_salvar();
    }//GEN-LAST:event_btn_salvarActionPerformed

    private void jList1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jList1KeyPressed
        // TODO add your handling code here:

    }//GEN-LAST:event_jList1KeyPressed

    private void jList1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jList1MouseClicked
        // TODO add your handling code here:
        mostrar_dados();
    }//GEN-LAST:event_jList1MouseClicked

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        procedimento_alterar();
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jList1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jList1KeyReleased
        // TODO add your handling code here:
        mostrar_dados();
    }//GEN-LAST:event_jList1KeyReleased

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_jButton6ActionPerformed

    private void txt_residencia_actualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_residencia_actualActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_residencia_actualActionPerformed

    private void txtnaturalidadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtnaturalidadeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtnaturalidadeActionPerformed

    private void cmb_provinciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmb_provinciaActionPerformed
        // TODO add your handling code here:
        setSubMuncipio();
    }//GEN-LAST:event_cmb_provinciaActionPerformed

    private void cmb_municipioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmb_municipioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmb_municipioActionPerformed

    private void cmb_paisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmb_paisActionPerformed
        // TODO add your handling code here:
        setSubProvincia();
    }//GEN-LAST:event_cmb_paisActionPerformed

    private void txt_doencaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_doencaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_doencaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EstudanteVisao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EstudanteVisao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EstudanteVisao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EstudanteVisao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new EstudanteVisao(id_user).setVisible(true);
//            }
//        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_salvar;
    private javax.swing.JComboBox<String> cmb_municipio;
    private javax.swing.JComboBox<String> cmb_pais;
    private javax.swing.JComboBox<String> cmb_profissao;
    private javax.swing.JComboBox<String> cmb_provincia;
    private javax.swing.JComboBox<String> cmb_sexo;
    private com.toedter.calendar.JDateChooser dc_data_nascimento;
    private com.toedter.calendar.JDateChooser dc_data_validade;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JList<String> jList1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSlider jSlider1;
    private javax.swing.JTabbedPane jTP_DP;
    private javax.swing.JLabel lb_foto;
    private javax.swing.JLabel lb_total_estudantes;
    private javax.swing.JTextField txtLocalTrabalho;
    private javax.swing.JTextField txtNomeEncarregado;
    private javax.swing.JTextField txtNomeMae;
    private javax.swing.JTextField txtNomePai;
    private javax.swing.JTextField txtTelefoneEncarregado;
    private javax.swing.JTextField txt_doenca;
    private javax.swing.JTextField txt_emial;
    private javax.swing.JTextField txt_iniciais_nome;
    private javax.swing.JTextField txt_nbi;
    private javax.swing.JTextField txt_nomeCompleto;
    private javax.swing.JTextField txt_numero_matricula;
    private javax.swing.JTextField txt_residencia_actual;
    private javax.swing.JTextField txt_telefone;
    private javax.swing.JTextField txtnaturalidade;
    private javax.swing.JTextField txtresidencia;
    // End of variables declaration//GEN-END:variables

    private void setComponentes() {

        //adicionar_estudantes_jList();
        cmb_sexo.setModel(new DefaultComboBoxModel(sexoDao.buscaTodos()));
        cmb_profissao.setModel(new DefaultComboBoxModel(profissaoDao.buscaTodos()));
        cmb_pais.setModel(new DefaultComboBoxModel(paisDao.buscaTodos()));
        setSubProvincia();
        setSubMuncipio();
        adicionar_estudantes_jList();
        mostrar_total_estudantes();

    }

    private void setSubProvincia() {
        try {
            cmb_provincia.setModel(new DefaultComboBoxModel(provinciaDao.buscaTodos(getIdPais())));
        } catch (Exception e) {
        }
    }

    private void setSubMuncipio() {
        try {
            cmb_municipio.setModel(new DefaultComboBoxModel(municipioDao.buscaTodos(getIdProvincia())));
        } catch (Exception e) {
        }
    }

    private int getIdSexo() {
        return sexoDao.getIdByDescricao(cmb_sexo.getSelectedItem().toString());
    }

    private int getIdProvincia() {
        return provinciaDao.getIdByDescricao(cmb_provincia.getSelectedItem().toString());
    }

    private int getIdPais() {
        return paisDao.getIdByDescricao(cmb_pais.getSelectedItem().toString());
    }

    private int getIdMunicipio() {
        return municipioDao.getIdByDescricao(cmb_municipio.getSelectedItem().toString());
    }

    private int getIdProfissao() {
        return profissaoDao.getIdByDescricao(cmb_profissao.getSelectedItem().toString());
    }

    private void adicionar_estudantes_jList() {

        List<Estudante> list = estudanteDao.buscaTodosEstudante();
        listModel.clear();
        try {
            for (int i = 0; i < list.size(); i++) {
                listModel.add(i, list.get(i).getNomeCompleto());
            }

        } catch (Exception e) {
        }

    }

    private void adicionar_estudantes_jList(List<Estudante> list) {

        listModel.clear();
        try {
            for (int i = 0; i < list.size(); i++) {
                listModel.add(i, list.get(i).getNomeCompleto());
            }

        } catch (Exception e) {
        }

    }

    private boolean validar_campos() {

        if (txt_nomeCompleto.getText().equals("")) {

            JOptionPane.showMessageDialog(null, "Pf digite o nome do estudante", "AVISO", JOptionPane.WARNING_MESSAGE);
//            jocMessageLabel1.setBusyForeground(Color.RED);
//            jocMessageLabel1.busyMessage("Pf digite o nome do estudante");
            jTP_DP.setSelectedIndex(0);
            txt_nomeCompleto.requestFocus();

            return false;

        } else if (cmb_sexo.getSelectedIndex() == 0) {
            JOptionPane.showMessageDialog(null, "Pf seleccione o sexo do estudante", "AVISO", JOptionPane.WARNING_MESSAGE);
            jTP_DP.setSelectedIndex(2);
            cmb_sexo.requestFocus();
            return false;

        } else if (dc_data_nascimento.getCalendar() == null) {
            JOptionPane.showMessageDialog(null, "Pf insira a data de nascimento do estudante", "AVISO", JOptionPane.WARNING_MESSAGE);
            jTP_DP.setSelectedIndex(0);
            dc_data_nascimento.requestFocus();
            return false;
        } else if (txt_nbi.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Pf digite o bilhete de idêntidade do estudante", "AVISO", JOptionPane.WARNING_MESSAGE);
            jTP_DP.setSelectedIndex(1);
            txt_nbi.requestFocus();
            return false;

        } else if (dc_data_validade.getCalendar() == null) {
            JOptionPane.showMessageDialog(null, "Pf insira a data de validade do BI", "AVISO", JOptionPane.WARNING_MESSAGE);
            jTP_DP.setSelectedIndex(0);
            dc_data_validade.requestFocus();
            return false;
        } else if (txt_residencia_actual.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Pf digite a residência actual do estudante", "AVISO", JOptionPane.WARNING_MESSAGE);
            jTP_DP.setSelectedIndex(0);
            txt_residencia_actual.requestFocus();
            return false;

        } else if (txt_doenca.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Pf digite digite Sim ou Não.", "AVISO", JOptionPane.WARNING_MESSAGE);
            jTP_DP.setSelectedIndex(0);
            txt_doenca.requestFocus();
            return false;

        } else if (txtnaturalidade.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Pf digite a naturalidade do estudante", "AVISO", JOptionPane.WARNING_MESSAGE);
            jTP_DP.setSelectedIndex(0);
            txtnaturalidade.requestFocus();
            return false;

        } else if (cmb_provincia.getSelectedIndex() == 0) {
            JOptionPane.showMessageDialog(null, "Pf seleccione a província do estudante", "AVISO", JOptionPane.WARNING_MESSAGE);
            jTP_DP.setSelectedIndex(2);
            cmb_provincia.requestFocus();
            return false;

        } else if (cmb_municipio.getSelectedIndex() == 0) {
            JOptionPane.showMessageDialog(null, "Pf seleccione o municipio do estudante", "AVISO", JOptionPane.WARNING_MESSAGE);
            jTP_DP.setSelectedIndex(2);
            cmb_municipio.requestFocus();
            return false;

        } else if (txt_telefone.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Pf digite o telefone do estudante", "AVISO", JOptionPane.WARNING_MESSAGE);
            jTP_DP.setSelectedIndex(0);
            txt_telefone.requestFocus();
            return false;

        } else if (txt_emial.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Pf digite o email do estudante", "AVISO", JOptionPane.WARNING_MESSAGE);
            jTP_DP.setSelectedIndex(0);
            txt_emial.requestFocus();
            return false;

        } else if (txtNomeEncarregado.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Pf digite o nome do Encarregado do estudante", "AVISO", JOptionPane.WARNING_MESSAGE);
            jTP_DP.setSelectedIndex(0);
            txtNomeEncarregado.requestFocus();
            return false;

        } else if (cmb_profissao.getSelectedIndex() == 0) {
            JOptionPane.showMessageDialog(null, "Pf seleccione a profissão do estudante", "AVISO", JOptionPane.WARNING_MESSAGE);
            jTP_DP.setSelectedIndex(2);
            cmb_profissao.requestFocus();
            return false;

        } else if (txtLocalTrabalho.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Pf digite o local de trabalho do Encarregado ", "AVISO", JOptionPane.WARNING_MESSAGE);
            jTP_DP.setSelectedIndex(0);
            txtLocalTrabalho.requestFocus();
            return false;

        } else if (txtresidencia.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Pf digite a residência do Encarregado ", "AVISO", JOptionPane.WARNING_MESSAGE);
            jTP_DP.setSelectedIndex(0);
            txtresidencia.requestFocus();
            return false;

        } else if (txtTelefoneEncarregado.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Pf digite o telefone do Encarregado", "AVISO", JOptionPane.WARNING_MESSAGE);
            jTP_DP.setSelectedIndex(0);
            txtTelefoneEncarregado.requestFocus();
            return false;

        } else if (txtNomePai.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Pf digite  o nome do Pai do estudante", "AVISO", JOptionPane.WARNING_MESSAGE);
            jTP_DP.setSelectedIndex(1);
            txtNomePai.requestFocus();
            return false;

        } else if (txtNomeMae.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Pf digite  o nome da Mãe do estudante", "AVISO", JOptionPane.WARNING_MESSAGE);
            jTP_DP.setSelectedIndex(1);
            txtNomeMae.requestFocus();
            return false;

        }

        return true;

    }

    private void limpar_campos() {

        lb_foto.setIcon(null);
        /* limpar a parte 1 */
        txt_numero_matricula.setText("");
        txt_nomeCompleto.setText("");
        cmb_sexo.setSelectedIndex(0);
        dc_data_nascimento.setDate(null);
        txt_nbi.setText("");
        dc_data_validade.setDate(null);
        txt_residencia_actual.setText("");
        txt_doenca.setText("");
        txtnaturalidade.setText("");
        cmb_provincia.setSelectedIndex(0);
        cmb_municipio.setSelectedIndex(0);
        txt_telefone.setText("");
        txt_emial.setText("");
        txtNomeEncarregado.setText("");
        cmb_profissao.setSelectedIndex(0);
        txtLocalTrabalho.setText("");
        txtresidencia.setText("");
        txtTelefoneEncarregado.setText("");
        txtNomePai.setText("");
        txtNomeMae.setText("");

    }

    private void setDadosEstudanteModelo() {

        /* parte 1*/
        try {
            this.estudante.setFoto(image_view.getBystebyteImg());
        } catch (Exception e) {
        }

        this.estudante.setNumeroMatricula(txt_numero_matricula.getText());
        this.estudante.setNomeCompleto(txt_nomeCompleto.getText());
        this.estudante.setFkSexo(sexoDao.findSexo(getIdSexo()));
        this.estudante.setDataNascimento(dc_data_nascimento.getDate());
        this.estudante.setNbi(txt_nbi.getText());
        this.estudante.setDataValidadeBI(dc_data_validade.getDate());
        this.estudante.setEndereco(txt_residencia_actual.getText());
        this.estudante.setDoenca(txt_doenca.getText());
        this.estudante.setNaturalidade(txtnaturalidade.getText());
        this.estudante.setFkMunicipio(municipioDao.findMunicipio(getIdMunicipio()));
        this.estudante.setTelefone(txt_telefone.getText());
        this.estudante.setEmail(txt_emial.getText());
        this.estudante.setNomePai(txtNomePai.getText());
        this.estudante.setNomeMae(txtNomeMae.getText());
        this.estudante.setFkEncarregado(encarregadoDao.getEncarregadoByTelefone(txtTelefoneEncarregado.getText()));

    }

    private void setDadosEstudanteModeloEditar() {

        /* parte 1*/
        try {
            this.estudante.setFoto(image_view.getBystebyteImg());
        } catch (Exception e) {
        }

        this.estudante.setNumeroMatricula(txt_numero_matricula.getText());
        this.estudante.setNomeCompleto(txt_nomeCompleto.getText());
        this.estudante.setFkSexo(sexoDao.findSexo(getIdSexo()));
        this.estudante.setDataNascimento(dc_data_nascimento.getDate());
        this.estudante.setNbi(txt_nbi.getText());
        this.estudante.setDataValidadeBI(dc_data_validade.getDate());
        this.estudante.setEndereco(txt_residencia_actual.getText());
        this.estudante.setDoenca(txt_doenca.getText());
        this.estudante.setNaturalidade(txtnaturalidade.getText());
        this.estudante.setFkMunicipio(municipioDao.findMunicipio(getIdMunicipio()));
        this.estudante.setTelefone(txt_telefone.getText());
        this.estudante.setEmail(txt_emial.getText());
        this.estudante.setNomePai(txtNomePai.getText());
        this.estudante.setNomeMae(txtNomeMae.getText());

    }

    private void setDadosEncarregadoModelo() {

        /* parte 1*/
        this.encarregado.setNomeCompleto(txtNomeEncarregado.getText());
        this.encarregado.setFkProfissao(profissaoDao.findProfissao(getIdProfissao()));
        this.encarregado.setLocalTrabalho(txtLocalTrabalho.getText());
        this.encarregado.setResidencia(txtresidencia.getText());
        this.encarregado.setTelefone(txtTelefoneEncarregado.getText());

    }

    private void procedimento_salvar() {

        if (validar_campos()) {

            if (!estudanteDao.exist_estudante(txt_nbi.getText())) {
                try {

                    this.estudante = new Estudante();
                    this.encarregado = new Encarregado();
                    setDadosEncarregadoModelo();
                    this.encarregadoDao.create(this.encarregado);
                    setDadosEstudanteModelo();
                    this.estudanteDao.create(this.estudante);

                    //mostrar_total_estudante();
                    adicionar_estudantes_jList();
                    limpar_campos();

                    JOptionPane.showMessageDialog(null, "Dados salvos com sucesso!...");
                    mostrar_total_estudantes();

                } catch (Exception e) {
                    e.printStackTrace();
                    JOptionPane.showMessageDialog(null, "Erro ao salvar o estudante", "ERRO", JOptionPane.ERROR_MESSAGE);
                }

            } else {
                JOptionPane.showMessageDialog(null, "Este estudante ja se encontra cadastrado no banco de dados", "ERRO", JOptionPane.ERROR_MESSAGE);
            }
        }

    }

    private void procedimento_alterar() {

        if (validar_campos()) {

            if (estudanteDao.exist_estudante(txt_nbi.getText())) {
                try {

                    Estudante estudante_historico = estudanteDao.findEstudante(this.id_estudante);
                    this.estudante = estudanteDao.findEstudante(this.id_estudante);
                    this.encarregado = this.estudante.getFkEncarregado();
                    setDadosEncarregadoModelo();
                    this.encarregadoDao.edit(this.encarregado);
                    setDadosEstudanteModeloEditar();
                    this.estudanteDao.edit(this.estudante);
                    // procedimento_salvar_historico(estudante_historico);
                    adicionar_estudantes_jList();
                    JOptionPane.showMessageDialog(null, "Dados alterados com sucesso!...");

                } catch (Exception e) {
                    JOptionPane.showMessageDialog(null, "Erro ao alterar o estudante", "ERRO", JOptionPane.ERROR_MESSAGE);
                }

            } else {
                JOptionPane.showMessageDialog(null, "Este estudante não existe impossivel alterar", "ERRO", JOptionPane.ERROR_MESSAGE);
            }
        }

    }

    private void eliminar() {

        int opcao = JOptionPane.showConfirmDialog(null, "Tens a certeza que pretendes eliminar este estudante ?");

        if (opcao == JOptionPane.YES_OPTION) {

            try {

                estudanteDao.destroy(this.id_estudante);
                adicionar_estudantes_jList();
                JOptionPane.showMessageDialog(null, "Funcionário removido com sucesso!...");
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, "Erro ao remover este estudante.\nPorque esta relacionado com as outras tabelas", "ERRO", JOptionPane.ERROR_MESSAGE);
            }

        } else {
            JOptionPane.showMessageDialog(null, "Operação cancelada", "INFOR", JOptionPane.INFORMATION_MESSAGE);
        }

    }

    //----------- evento do teclado ---------------------------------------
    class TratarEventoTeclado implements KeyListener {

        String prefixo = "";

        public void keyPressed(KeyEvent evt) {

            if (evt.getKeyCode() != KeyEvent.VK_BACK_SPACE && evt.getKeyCode() != KeyEvent.VK_ENTER) {
                char key = evt.getKeyChar();

                try {

                    prefixo = txt_iniciais_nome.getText().trim() + key;
                    adicionar_estudantes_jList(estudanteDao.getALLEstudante_LIKE_nomeCompleto(prefixo));

                } catch (Exception e) {
                    e.printStackTrace();
                    limpar_campos();
                }

            } else if (evt.getKeyCode() == KeyEvent.VK_BACK_SPACE) {
                try {

                    prefixo = prefixo.toString().trim().substring(0, prefixo.length() - 1);
                    adicionar_estudantes_jList(estudanteDao.getALLEstudante_LIKE_nomeCompleto(prefixo));

                } catch (Exception e) {
                    limpar_campos();
                }

            }
        }

        public void keyReleased(KeyEvent evt) {
        }

        public void keyTyped(KeyEvent evt) {
        }

    }

    private void mostrar_dados() {

        Estudante object = estudanteDao.getEstudanteByNome(jList1.getSelectedValue().toString());

        this.id_estudante = object.getPkEstudante();

        try {
            imageIcon = new ImageIcon(object.getFoto());
            imageIcon.setImage(imageIcon.getImage().getScaledInstance(138, 140, 100));
            lb_foto.setIcon(imageIcon);
        } catch (Exception e) {
            lb_foto.setIcon(null);
        }

        /* limpar a parte 1 */
        txt_numero_matricula.setText(object.getNumeroMatricula());
        txt_nomeCompleto.setText(object.getNomeCompleto());
        dc_data_validade.setDate(object.getDataNascimento());
        txt_telefone.setText(object.getTelefone());
        txt_emial.setText(object.getEmail());
        txt_residencia_actual.setText(object.getEndereco());
        txt_doenca.setText(object.getDoenca());
        txt_nbi.setText(object.getNbi());
        dc_data_nascimento.setDate(object.getDataNascimento());
        cmb_sexo.setSelectedItem(object.getFkSexo().getDesignacao());
        txtnaturalidade.setText(object.getNaturalidade());
        txtNomePai.setText(object.getNomePai());
        txtNomeMae.setText(object.getNomeMae());

        /**
         * Carrega os dados do municipio, província e país.
         */
        Municipio municipio = object.getFkMunicipio();

        cmb_pais.setSelectedItem(municipio.getFkProvincia().getFkPais().getDesignacao());
        cmb_provincia.setSelectedItem(municipio.getFkProvincia().getDesignacao());
        cmb_municipio.setSelectedItem(municipio.getDesignacao());

        /**
         * Carrega os dados do encaregado.
         */
        Encarregado encarregado = object.getFkEncarregado();

        txtNomeEncarregado.setText(encarregado.getNomeCompleto());
        cmb_profissao.setSelectedItem(encarregado.getFkProfissao().getDesignacao());
        txtLocalTrabalho.setText(encarregado.getLocalTrabalho());
        txtresidencia.setText(encarregado.getResidencia());
        txtTelefoneEncarregado.setText(encarregado.getTelefone());

    }

    private void mostrar_dados(Estudante object) {

        this.id_estudante = object.getPkEstudante();

        try {
            imageIcon = new ImageIcon(object.getFoto());
            imageIcon.setImage(imageIcon.getImage().getScaledInstance(138, 140, 100));
            lb_foto.setIcon(imageIcon);
        } catch (Exception e) {
            lb_foto.setIcon(null);
        }

        /* limpar a parte 1 */
        txt_nomeCompleto.setText(object.getNomeCompleto());

        dc_data_validade.setDate(object.getDataNascimento());

        txt_telefone.setText(object.getTelefone());
        txt_emial.setText(object.getEmail());

        txt_residencia_actual.setText(object.getEndereco());
        txt_doenca.setText(object.getDoenca());

        /* limpar parte 2 */
        txt_nbi.setText(object.getNbi());

    }

//    private void procedimento_pesquisa(){
//            
//        
//        
//        if (!txt_pesquisa.getText().equals("")) {
//                        
//             if( cmbPesquisa.getSelectedIndex() == 0  ) {
//                 
//                  Estudante estudante = estudanteDao.getEstudanteByBI(    txt_pesquisa.getText()  );
//                  try {
//                     listModel.clear();
//                     listModel.add(0, estudante.getNomeCompleto());                        
//                     mostrar_dados(estudante);
//                 } catch (Exception e) {
//                     limpar_campos();
//                     JOptionPane.showMessageDialog(null, "Não há estudante relacionado a esta pesquisa");
//                 }
//                  
//           
//             }
//             
//             
//             else if( cmbPesquisa.getSelectedIndex() == 1  ) {
//                 
//                  Estudante estudante = estudanteDao.getEstudanteByPassPort(    txt_pesquisa.getText()  );
//                  try {
//                     listModel.clear();
//                     listModel.add(0, estudante.getNomeCompleto());                        
//                     mostrar_dados(estudante);
//                 } catch (Exception e) {
//                     limpar_campos();
//                     JOptionPane.showMessageDialog(null, "Não há estudante relacionado a esta pesquisa");
//                 }
//                  
//           
//             }
//             else if( cmbPesquisa.getSelectedIndex() == 2  ) {
//                 
//                  Estudante estudante = estudanteDao.getEstudanteByCartaConducao(txt_pesquisa.getText()  );
//                  try {
//                     listModel.clear();
//                     listModel.add(0, estudante.getNomeCompleto());                        
//                     mostrar_dados(estudante);
//                 } catch (Exception e) {
//                     limpar_campos();
//                     JOptionPane.showMessageDialog(null, "Não há estudante relacionado a esta pesquisa");
//                 }
//           
//             }
//            
//       }else JOptionPane.showMessageDialog(null, "Por favor digite o dado para pesquisar");
//        
//    }
    public void persist(Object object) {
        EntityManager em = emf.createEntityManager();
        em.getTransaction().begin();
        try {
            em.persist(object);
            em.getTransaction().commit();
        } catch (Exception e) {
            e.printStackTrace();
            em.getTransaction().rollback();
        } finally {
            em.close();
        }
    }

    private void mostrar_total_estudantes() {

        try {
             lb_total_estudantes.setText(String.valueOf(estudanteDao.getTotalEstudante()));
        } catch (Exception e) {
            lb_total_estudantes.setText("0");
        }
       

    }

}
