/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package visao;

import dao.AnoLectivoDao;
import dao.ClasseDao;
import dao.ConfirmacaoMatriculaDao;
import dao.CursoDao;
import dao.PrecoPropinaDao;
import dao.PropinaDao;
import dao.TurmaDao;
import entity.Estudante;
import entity.Turma;
import ireport.MapaPropinasREPORT;
import java.util.ArrayList;
import java.util.List;
import java.util.Vector;
import javax.persistence.EntityManagerFactory;
import javax.swing.DefaultComboBoxModel;
import util.JPAEntntityMannagerFactoryUtil;
import util.MapaApontamentoPropinaUtil;

/**
 *
 * @author Domingos Dala Vunge
 */
public class MapaApontamentoPropinaVisao extends javax.swing.JFrame
{

    private final EntityManagerFactory emf = JPAEntntityMannagerFactoryUtil.em;
    private final AnoLectivoDao anoLectivoDao = new AnoLectivoDao( emf );
    private final ConfirmacaoMatriculaDao confirmacaoMatriculaDao = new ConfirmacaoMatriculaDao( emf );
    private final ClasseDao classeDao = new ClasseDao( emf );
    private final PropinaDao propinaDao = new PropinaDao( emf );
    private final CursoDao cursoDao = new CursoDao( emf );
    private final TurmaDao turmaDao = new TurmaDao( emf );
    private final PrecoPropinaDao precoPropinaDao = new PrecoPropinaDao( emf );

    public MapaApontamentoPropinaVisao()
    {
        initComponents();
        setLocationRelativeTo( null );
        setCampos();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings( "unchecked" )
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        cmbTurma = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        cmbCurso = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        cmbClasse = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        cmb_anoLectivo = new javax.swing.JComboBox<>();
        jLabel10 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/proucura.png"))); // NOI18N
        jButton1.setText("Visualizar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Logout 32x32.png"))); // NOI18N
        jButton2.setText("Sair");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton2)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        cmbTurma.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        cmbTurma.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cmbTurma.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cmbTurmaMouseClicked(evt);
            }
        });
        cmbTurma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbTurmaActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Lucida Grande", 1, 12)); // NOI18N
        jLabel8.setText("Turma:");

        jLabel9.setFont(new java.awt.Font("Lucida Grande", 1, 12)); // NOI18N
        jLabel9.setText("Curso:");

        cmbCurso.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        cmbCurso.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cmbCurso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbCursoActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Lucida Grande", 1, 12)); // NOI18N
        jLabel7.setText("Classe:");

        cmbClasse.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        cmbClasse.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cmbClasse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbClasseActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Lucida Grande", 1, 12)); // NOI18N
        jLabel5.setText("Ano Lectivo:");

        cmb_anoLectivo.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        cmb_anoLectivo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cmb_anoLectivo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmb_anoLectivoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, 96, Short.MAX_VALUE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cmb_anoLectivo, 0, 174, Short.MAX_VALUE)
                    .addComponent(cmbClasse, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(cmbCurso, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(42, 42, 42))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cmbTurma, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(27, 27, 27))))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmb_anoLectivo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmbCurso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cmbClasse, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cmbTurma, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(17, Short.MAX_VALUE))
        );

        jLabel10.setBackground(new java.awt.Color(192, 208, 232));
        jLabel10.setFont(new java.awt.Font("Lucida Grande", 1, 25)); // NOI18N
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("MAPA DE APONTAMENTO DE PROPINAS");
        jLabel10.setOpaque(true);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, 595, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cmbTurmaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cmbTurmaMouseClicked
        // TODO add your handling code here:

        //adicionar_estudantes_jList(  confirmacaoMatriculaDao.getAllEstudantesByTurma(getIdTurma()) );
    }//GEN-LAST:event_cmbTurmaMouseClicked

    private void cmbTurmaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbTurmaActionPerformed
        // TODO add your handling code here:
        //mostra_estudantes_por_turma();

    }//GEN-LAST:event_cmbTurmaActionPerformed

    private void cmbCursoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbCursoActionPerformed
        // TODO add your handling code here:
        mostra_turma_por_ClasseAnoCurso();

    }//GEN-LAST:event_cmbCursoActionPerformed

    private void cmbClasseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbClasseActionPerformed
        // TODO add your handling code here:
        mostra_turma_por_ClasseAnoCurso();
    }//GEN-LAST:event_cmbClasseActionPerformed

    private void cmb_anoLectivoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmb_anoLectivoActionPerformed
        // TODO add your handling code here:
        mostra_turma_por_ClasseAnoCurso();
    }//GEN-LAST:event_cmb_anoLectivoActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        procedimento_vusualizar();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main( String args[] )
    {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try
        {
            for ( javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels() )
            {
                if ( "Windows".equals( info.getName() ) )
                {
                    javax.swing.UIManager.setLookAndFeel( info.getClassName() );
                    break;
                }
            }
        }
        catch ( ClassNotFoundException ex )
        {
            java.util.logging.Logger.getLogger( MapaApontamentoPropinaVisao.class.getName() ).log( java.util.logging.Level.SEVERE, null, ex );
        }
        catch ( InstantiationException ex )
        {
            java.util.logging.Logger.getLogger( MapaApontamentoPropinaVisao.class.getName() ).log( java.util.logging.Level.SEVERE, null, ex );
        }
        catch ( IllegalAccessException ex )
        {
            java.util.logging.Logger.getLogger( MapaApontamentoPropinaVisao.class.getName() ).log( java.util.logging.Level.SEVERE, null, ex );
        }
        catch ( javax.swing.UnsupportedLookAndFeelException ex )
        {
            java.util.logging.Logger.getLogger( MapaApontamentoPropinaVisao.class.getName() ).log( java.util.logging.Level.SEVERE, null, ex );
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater( new Runnable()
        {
            public void run()
            {
                new MapaApontamentoPropinaVisao().setVisible( true );
            }
        } );
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cmbClasse;
    private javax.swing.JComboBox<String> cmbCurso;
    private javax.swing.JComboBox<String> cmbTurma;
    private javax.swing.JComboBox<String> cmb_anoLectivo;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    // End of variables declaration//GEN-END:variables

    private void mostra_turma_por_ClasseAnoCurso()
    {
        try
        {
            cmbTurma.setModel( new DefaultComboBoxModel( ( Vector ) turmaDao.buscaTodasTurmasByCursoAnoClasse( getIdClasse(), getIdAno(), getIdCurso() ) ) );
        }
        catch ( Exception e )
        {
            e.printStackTrace();
        }

    }

    private int getIdCurso()
    {
        return cursoDao.getIdByDescricao( cmbCurso.getSelectedItem().toString() );
    }

    private int getIdClasse()
    {
        return classeDao.getPkByDescricao( cmbClasse.getSelectedItem().toString() );
    }

    private int getIdAno()
    {
        return anoLectivoDao.getIdByDescricao( cmb_anoLectivo.getSelectedItem().toString() );
    }

    private int getIdTurma()
    {
        return turmaDao.getPkByDescricao( cmbTurma.getSelectedItem().toString() );
    }

    private void setCampos()
    {

        cmb_anoLectivo.setModel( new DefaultComboBoxModel( anoLectivoDao.buscaTodos() ) );
        cmbClasse.setModel( new DefaultComboBoxModel( classeDao.buscaTodos() ) );
        cmbCurso.setModel( new DefaultComboBoxModel( cursoDao.buscaTodos() ) );
        cmbTurma.setModel( new DefaultComboBoxModel( ( Vector ) turmaDao.buscaTodos() ) );

    }

    private void procedimento_vusualizar()
    {

        /**
         * @primerio: buscar todos os estudantes de uma determinada turma
         * @segundo: para cada estudante verificar o último pagamento pago
         * @terceiro: adicionar na lista cada estudante
         */
        List<Estudante> lista_estudante = confirmacaoMatriculaDao.buscaTodosEstudanteConfirmadosByIdTurma( getIdTurma() );
        List<MapaApontamentoPropinaUtil> list_mapa = new ArrayList<>();
        Turma turma = turmaDao.findTurma( getIdTurma() );
        int id_preco_propina = precoPropinaDao.getLastId( turma.getFkClasse().getPkClasse(), turma.getFkCurso().getPkCurso() );
        double preco_propina = precoPropinaDao.findPrecoPropina( id_preco_propina ).getValor();
        int ultimo_mes_pago = 0;
        for ( Estudante estudante : lista_estudante )
        {
            ultimo_mes_pago = propinaDao.getLastUltimoMes( estudante.getPkEstudante() );
            list_mapa.add( getObjecto( estudante, preco_propina, ultimo_mes_pago ) );
        }

        MapaPropinasREPORT mapaPropinasREPORT = new MapaPropinasREPORT( list_mapa, turma );

    }

    private MapaApontamentoPropinaUtil getObjecto( Estudante estudante, double preco, int ultimo_mes_pago )
    {

        MapaApontamentoPropinaUtil object = new MapaApontamentoPropinaUtil();

        int numero_matricula;
        try
        {
            numero_matricula = Integer.parseInt( estudante.getNumeroMatricula() );
        }
        catch ( NumberFormatException e )
        {
            e.printStackTrace();
            numero_matricula = 0;
        }

        object.setNome_completo( estudante.getNomeCompleto() );
        object.setNumero_matricula( numero_matricula );
        object.setSexo( estudante.getFkSexo().getDesignacao() );

        switch ( ultimo_mes_pago )
        {
            case 1:
            {
                object.setFev( preco );
            }
            break;
            case 2:
            {
                object.setFev( preco );
                object.setMar( preco );
            }
            break;
            case 3:
            {
                object.setFev( preco );
                object.setMar( preco );
                object.setAbr( preco );
            }
            break;
            case 4:
            {
                object.setFev( preco );
                object.setMar( preco );
                object.setAbr( preco );
                object.setMai( preco );
            }
            break;
            case 5:
            {
                object.setFev( preco );
                object.setMar( preco );
                object.setAbr( preco );
                object.setMai( preco );
                object.setJun( preco );
            }
            break;
            case 6:
            {
                object.setFev( preco );
                object.setMar( preco );
                object.setAbr( preco );
                object.setMai( preco );
                object.setJun( preco );
                object.setJul( preco );
            }
            break;
            case 7:
            {
                object.setFev( preco );
                object.setMar( preco );
                object.setAbr( preco );
                object.setMai( preco );
                object.setJun( preco );
                object.setJul( preco );
                object.setAgo( preco );
            }
            break;
            case 8:
            {
                object.setFev( preco );
                object.setMar( preco );
                object.setAbr( preco );
                object.setMai( preco );
                object.setJun( preco );
                object.setJul( preco );
                object.setAgo( preco );
                object.setSet( preco );
            }
            break;
            case 9:
            {
                object.setFev( preco );
                object.setMar( preco );
                object.setAbr( preco );
                object.setMai( preco );
                object.setJun( preco );
                object.setJul( preco );
                object.setAgo( preco );
                object.setSet( preco );
                object.setNov( preco );
            }
            break;
            case 10:
            {
                object.setFev( preco );
                object.setMar( preco );
                object.setAbr( preco );
                object.setMai( preco );
                object.setJun( preco );
                object.setJul( preco );
                object.setAgo( preco );
                object.setSet( preco );
                object.setOut( preco );
                object.setNov( preco );
            }
            break;
            case 11:
            {
                object.setFev( preco );
                object.setMar( preco );
                object.setAbr( preco );
                object.setMai( preco );
                object.setJun( preco );
                object.setJul( preco );
                object.setAgo( preco );
                object.setSet( preco );
                object.setOut( preco );
                object.setNov( preco );
                object.setDez( preco );
            }
            break;

        }

        return object;

    }

}
